# Cursor API Proxy Worker配置
name = "ccc"
main = "worker.js"
compatibility_date = "2024-02-15"

# KV命名空间配置
# 使用以下命令创建KV命名空间:
# wrangler kv:namespace create "TOKENS"
# 然后将输出的id替换下面的<YOUR_KV_NAMESPACE_ID>
#
kv_namespaces = [
  { binding = "TOKENS", id = "0697c18ff40948fcb897fb0587eb91b2" }
]

# 环境变量
[vars]
MASTER_KEY = "sk-chatify-MoLu154!" 